--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/8/2021 3:15:19 PM
-- Server version: 8.0.24
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ukrabobus_db;

--
-- Drop table `tickets`
--
DROP TABLE IF EXISTS tickets;

--
-- Drop table `document_types`
--
DROP TABLE IF EXISTS document_types;

--
-- Drop table `passangers`
--
DROP TABLE IF EXISTS passangers;

--
-- Drop table `types_of_class`
--
DROP TABLE IF EXISTS types_of_class;

--
-- Drop table `timetables`
--
DROP TABLE IF EXISTS timetables;

--
-- Drop table `transports`
--
DROP TABLE IF EXISTS transports;

--
-- Drop table `transport_types`
--
DROP TABLE IF EXISTS transport_types;

--
-- Set default database
--
USE ukrabobus_db;

--
-- Create table `transport_types`
--
CREATE TABLE transport_types (
  id int NOT NULL AUTO_INCREMENT,
  type varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `transports`
--
CREATE TABLE transports (
  id int NOT NULL AUTO_INCREMENT,
  id_transport_type int NOT NULL,
  number_of_econom int NOT NULL,
  number_of_standart int NOT NULL,
  number_of_comfort int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE transports
ADD CONSTRAINT FK_transports_id_transport_type FOREIGN KEY (id_transport_type)
REFERENCES transport_types (id);

--
-- Create table `timetables`
--
CREATE TABLE timetables (
  id int NOT NULL AUTO_INCREMENT,
  city_from varchar(255) NOT NULL,
  city_to varchar(255) NOT NULL,
  arrival_time time NOT NULL,
  departure_time time NOT NULL,
  id_transport int NOT NULL,
  date date NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE timetables
ADD CONSTRAINT FK_timetables_id_transport FOREIGN KEY (id_transport)
REFERENCES transports (id);

--
-- Create table `types_of_class`
--
CREATE TABLE types_of_class (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  description varchar(255) NOT NULL,
  price decimal(19, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `passangers`
--
CREATE TABLE passangers (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  sname varchar(255) NOT NULL,
  `e-mail` varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `document_types`
--
CREATE TABLE document_types (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  discount int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `tickets`
--
CREATE TABLE tickets (
  id int NOT NULL AUTO_INCREMENT,
  id_passanger int NOT NULL,
  id_transport int NOT NULL,
  number_of_passangers int NOT NULL,
  id_type int NOT NULL,
  price decimal(19, 2) NOT NULL,
  id_document int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_document FOREIGN KEY (id_document)
REFERENCES document_types (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_passanger FOREIGN KEY (id_passanger)
REFERENCES passangers (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_transport FOREIGN KEY (id_transport)
REFERENCES transports (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_type FOREIGN KEY (id_type)
REFERENCES types_of_class (id);

-- 
-- Dumping data for table transport_types
--
-- Table ukrabobus_db.transport_types does not contain any data (it is empty)

-- 
-- Dumping data for table types_of_class
--
-- Table ukrabobus_db.types_of_class does not contain any data (it is empty)

-- 
-- Dumping data for table transports
--
-- Table ukrabobus_db.transports does not contain any data (it is empty)

-- 
-- Dumping data for table passangers
--
-- Table ukrabobus_db.passangers does not contain any data (it is empty)

-- 
-- Dumping data for table document_types
--
-- Table ukrabobus_db.document_types does not contain any data (it is empty)

-- 
-- Dumping data for table timetables
--
-- Table ukrabobus_db.timetables does not contain any data (it is empty)

-- 
-- Dumping data for table tickets
--
-- Table ukrabobus_db.tickets does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;