--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date Ср 08.12.21 16:07:29
-- Server version: 8.0.24
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ukrabobus_db;

--
-- Drop table `tickets`
--
DROP TABLE IF EXISTS tickets;

--
-- Drop table `document_types`
--
DROP TABLE IF EXISTS document_types;

--
-- Drop table `passangers`
--
DROP TABLE IF EXISTS passangers;

--
-- Drop table `types_of_class`
--
DROP TABLE IF EXISTS types_of_class;

--
-- Drop table `timetables`
--
DROP TABLE IF EXISTS timetables;

--
-- Drop table `transports`
--
DROP TABLE IF EXISTS transports;

--
-- Drop table `transport_types`
--
DROP TABLE IF EXISTS transport_types;

--
-- Set default database
--
USE ukrabobus_db;

--
-- Create table `transport_types`
--
CREATE TABLE transport_types (
  id int NOT NULL AUTO_INCREMENT,
  type varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `transports`
--
CREATE TABLE transports (
  id int NOT NULL AUTO_INCREMENT,
  id_transport_type int NOT NULL,
  number_of_econom int NOT NULL,
  number_of_standart int NOT NULL,
  number_of_comfort int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE transports
ADD CONSTRAINT FK_transports_id_transport_type FOREIGN KEY (id_transport_type)
REFERENCES transport_types (id);

--
-- Create table `timetables`
--
CREATE TABLE timetables (
  id int NOT NULL AUTO_INCREMENT,
  city_from varchar(255) NOT NULL,
  city_to varchar(255) NOT NULL,
  arrival_time time NOT NULL,
  departure_time time NOT NULL,
  id_transport int DEFAULT NULL,
  date date DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE timetables
ADD CONSTRAINT FK_timetables_id_transport FOREIGN KEY (id_transport)
REFERENCES transports (id);

--
-- Create table `types_of_class`
--
CREATE TABLE types_of_class (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  price decimal(19, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `passangers`
--
CREATE TABLE passangers (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  sname varchar(255) NOT NULL,
  `e-mail` varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `document_types`
--
CREATE TABLE document_types (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  discount decimal(10, 1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `tickets`
--
CREATE TABLE tickets (
  id int NOT NULL AUTO_INCREMENT,
  id_passanger int NOT NULL,
  id_transport int NOT NULL,
  number_of_passangers int NOT NULL,
  id_type int NOT NULL,
  price decimal(19, 2) NOT NULL,
  id_document int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_document FOREIGN KEY (id_document)
REFERENCES document_types (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_passanger FOREIGN KEY (id_passanger)
REFERENCES passangers (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_transport FOREIGN KEY (id_transport)
REFERENCES transports (id);

--
-- Create foreign key
--
ALTER TABLE tickets
ADD CONSTRAINT FK_tickets_id_type FOREIGN KEY (id_type)
REFERENCES types_of_class (id);

-- 
-- Dumping data for table transport_types
--
INSERT INTO transport_types VALUES
(1, 'Поїзд'),
(2, 'Літак'),
(3, 'Автобус');

-- 
-- Dumping data for table types_of_class
--
INSERT INTO types_of_class VALUES
(1, 'Економ', 150.00),
(2, 'Стандарт', 250.00),
(3, 'Комфорт', 500.00);

-- 
-- Dumping data for table transports
--
INSERT INTO transports VALUES
(1, 1, 10, 12, 15),
(2, 2, 8, 9, 10),
(3, 3, 20, 25, 15);

-- 
-- Dumping data for table passangers
--
-- Table ukrabobus_db.passangers does not contain any data (it is empty)

-- 
-- Dumping data for table document_types
--
INSERT INTO document_types VALUES
(1, 'Дорослий', 1.0),
(2, 'Дитячий', 0.5),
(3, 'Студентський', 0.5),
(4, 'Пільговий', 0.7);

-- 
-- Dumping data for table timetables
--
INSERT INTO timetables VALUES
(1, 'Київ', 'Львов', '12:57:07', '18:59:26', NULL, NULL),
(2, 'Львов', 'Київ', '21:05:07', '07:48:07', NULL, NULL);

-- 
-- Dumping data for table tickets
--
-- Table ukrabobus_db.tickets does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;